services:
  web:
    container_name: capstone-project-web
    image: node:20-alpine
    working_dir: /app/web
    ports:
      - '5001:5173'
    volumes:
      - ./web:/app/web
    command: [ "npm", "run", "dev", "--", "--host" ]

  api:
    container_name: capstone-project-api
    image: node:20-alpine
    working_dir: /app/api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app/api
    command: [ "npm", "run", "dev" ]
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: capstone-project-db
    image: postgres:17
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d default" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdb:
